export type CategoryId = 'models' | 'images' | 'video' | 'audio' | 'agents' | 'open';

export type TimelineEvent = {
  id: string;
  year: string;
  date: string;
  name: string;
  tag: string;
  line: string;
  detail: string;
  source: string;
  category: CategoryId;
  tier: 'major' | 'minor';
  visual?: 'chat' | 'image';
};

// 全站展品的唯一数据源；date 用 ISO 格式，展示格式由 dateLabel 等负责。
// tier: major = 时间线大卡片；minor = 紧凑单行。
export const events: TimelineEvent[] = (
  [
    // ── 2022 ──────────────────────────────────────────────
    {
      id: 'dalle-2',
      year: '2022',
      date: '2022-04-06',
      name: 'DALL-E 2',
      tag: '文生图初啼',
      line: '文字第一次变成了像样的画。',
      detail:
        'OpenAI 发布 DALL-E 2，文字生成图像的质量大幅跃升；内测邀请码让它先成为社交货币，再成为工具。',
      source: 'https://openai.com/dall-e-2/',
      category: 'images',
      tier: 'minor',
      visual: 'image',
    },
    {
      id: 'github-copilot-ga',
      year: '2022',
      date: '2022-06-21',
      name: 'GitHub Copilot 正式订阅',
      tag: '付费先行',
      line: 'ChatGPT 之前，程序员先交了钱。',
      detail:
        'GitHub Copilot 结束技术预览转为正式订阅，AI 编程助手第一次成为大众商品，也让“为 AI 付月费”提前被接受。',
      source: 'https://github.blog/news-insights/company-news/github-copilot-is-generally-available-to-all-developers/',
      category: 'agents',
      tier: 'minor',
    },
    {
      id: 'midjourney-beta',
      year: '2022',
      date: '2022-07-12',
      name: 'Midjourney 开放测试',
      tag: '社区炼图',
      line: 'Discord 的聊天框里，长出了一个画室。',
      detail:
        'Midjourney 向公众开放测试，凭免安装的社区体验迅速聚集创作者，与同期发布的 Stable Diffusion 分庭抗礼。',
      source: 'https://en.wikipedia.org/wiki/Midjourney',
      category: 'images',
      tier: 'minor',
    },
    {
      id: 'stable-diffusion',
      year: '2022',
      date: '2022-08-22',
      name: 'Stable Diffusion',
      tag: '图像生成',
      line: '把一句话，变成一幅画。',
      detail:
        'Stable Diffusion 公开发布，让更多人能够在自己的设备上探索文字生成图像。展品来自 CompVis 官方仓库，保留原始样貌。',
      source: 'https://stability.ai/news-updates/stable-diffusion-public-release',
      category: 'images',
      tier: 'major',
      visual: 'image',
    },
    {
      id: 'character-ai',
      year: '2022',
      date: '2022-09-16',
      name: 'Character.AI 公测',
      tag: 'AI 陪伴',
      line: '有人开始和 AI 角色聊到深夜。',
      detail:
        '前谷歌工程师创立的 Character.AI 开放公测，“和角色对话”成为一种新的陪伴方式，也埋下日后 AI 陪伴赛道的种子。',
      source: 'https://en.wikipedia.org/wiki/Character.ai',
      category: 'models',
      tier: 'minor',
    },
    {
      id: 'whisper',
      year: '2022',
      date: '2022-09-21',
      name: 'Whisper 开源',
      tag: '听写自由',
      line: '机器的耳朵，突然免费了。',
      detail: 'OpenAI 开源语音识别模型 Whisper，多语言转写从此人人可用，播客与访谈的整理成本一夜归零。',
      source: 'https://github.com/openai/whisper',
      category: 'audio',
      tier: 'minor',
    },
    {
      id: 'chatgpt',
      year: '2022',
      date: '2022-11-30',
      name: 'ChatGPT',
      tag: '对话的起点',
      line: '一个输入框，打开了一个新世界。',
      detail:
        'ChatGPT 以研究预览的形式上线。人们开始尝试让它写文章、解释概念和修改代码，同时也遇到它自信却不正确的回答。',
      source: 'https://openai.com/index/chatgpt/',
      category: 'models',
      tier: 'major',
      visual: 'chat',
    },
    {
      id: 'lensa',
      year: '2022',
      date: '2022-12-01',
      name: 'Lensa AI 头像狂潮',
      tag: '头像热潮',
      line: '第一次，大家排队让 AI 画自己。',
      detail:
        'Prisma 的 Lensa 掀起 AI 头像风潮，也带来第一批“我上传的照片去了哪”的隐私讨论。',
      source: 'https://prisma-ai.com/lensa',
      category: 'images',
      tier: 'minor',
    },
    {
      id: 'chatgpt-1m',
      year: '2022',
      date: '2022-12-05',
      name: 'ChatGPT 五天百万用户',
      tag: '现象时刻',
      line: '一个网址，五天，一百万人。',
      detail:
        '上线五天用户破百万，Altman 在社交媒体晒出增长曲线；“增长最快的消费级应用”的叙事由此改写。',
      source: 'https://en.wikipedia.org/wiki/ChatGPT',
      category: 'models',
      tier: 'major',
    },
    // ── 2023 ──────────────────────────────────────────────
    {
      id: 'ms-openai-investment',
      year: '2023',
      date: '2023-01-23',
      name: '微软投资 OpenAI 百亿美元',
      tag: '巨头下注',
      line: '一百亿美元，投给一个“研究预览”。',
      detail:
        '微软宣布与 OpenAI 扩大合作，多年期投资据报道达百亿美元量级，AI 军备竞赛的资本时代正式开启。',
      source: 'https://blogs.microsoft.com/blog/2023/01/23/microsoftandopenaiextendpartnership/',
      category: 'models',
      tier: 'minor',
    },
    {
      id: 'elevenlabs',
      year: '2023',
      date: '2023-01-23',
      name: 'ElevenLabs 声音克隆',
      tag: '以假乱真',
      line: '三秒样本，复刻人声。',
      detail:
        '声音克隆开放测试，逼真度令人惊叹，也带来第一批深度伪造语音的滥用警告。',
      source: 'https://elevenlabs.io',
      category: 'audio',
      tier: 'minor',
    },
    {
      id: 'chatgpt-100m',
      year: '2023',
      date: '2023-02-01',
      name: 'ChatGPT 两个月破亿',
      tag: '破亿纪录',
      line: 'TikTok 用了九个月，它只用了两个月。',
      detail:
        'UBS 研报显示 ChatGPT 上线约两个月月活破亿，成为当时史上增长最快的消费级应用。',
      source: 'https://www.reuters.com/technology/chatgpt-sets-record-fastest-growing-user-group-analyst-note-2023-02-01/',
      category: 'models',
      tier: 'major',
    },
    {
      id: 'new-bing',
      year: '2023',
      date: '2023-02-07',
      name: 'New Bing 发布',
      tag: '搜索宣战',
      line: '谷歌连夜开发布会，微软开了一场得意的。',
      detail:
        '微软把新一代模型装进 Bing 与 Edge，搜索引擎大战重新开打，“AI 会杀死搜索”第一次成为严肃话题。',
      source: 'https://blogs.microsoft.com/blog/2023/02/07/reinventing-search-with-a-new-ai-powered-microsoft-bing-and-edge-your-copilot-for-the-web/',
      category: 'agents',
      tier: 'minor',
    },
    {
      id: 'bard-fail',
      year: '2023',
      date: '2023-02-08',
      name: 'Bard 首秀翻车',
      tag: '幻觉示众',
      line: '一张宣传图里的天文错误，蒸发了千亿市值。',
      detail:
        '谷歌 Bard 首支演示视频中出现事实错误，股价应声大跌；大众第一次直观看到“AI 会一本正经地胡说”。',
      source: 'https://www.reuters.com/technology/alphabet-shares-slide-after-google-ai-chatbots-error-first-demo-2023-02-08/',
      category: 'models',
      tier: 'major',
    },
    {
      id: 'llama-leak',
      year: '2023',
      date: '2023-02-24',
      name: 'LLaMA 发布与泄露',
      tag: '权重出走',
      line: '一份研究权重流进论坛，一周之内羊驼遍地。',
      detail:
        'Meta 以研究许可发布 LLaMA，数日后权重泄露至社区；斯坦福以约六百美元微调出 Alpaca，开源微调浪潮就此引爆。',
      source: 'https://arxiv.org/abs/2302.13971',
      category: 'open',
      tier: 'major',
    },
    {
      id: 'claude-1',
      year: '2023',
      date: '2023-03-14',
      name: 'Claude 1：与 GPT-4 同日亮相',
      tag: '同日亮相',
      line: 'GPT-4 发布的那个下午，Anthropic 也掏出了 Claude。',
      detail:
        '前 OpenAI 成员创立的 Anthropic 发布 Claude 1，安全优先的路线自此与“能力优先”分庭抗礼。',
      source: 'https://www.anthropic.com/news/introducing-claude',
      category: 'models',
      tier: 'minor',
    },
    {
      id: 'gpt-4',
      year: '2023',
      date: '2023-03-14',
      name: 'GPT-4',
      tag: '能力的跃迁',
      line: '这一次，问题可以再难一点。',
      detail:
        'GPT-4 发布，展示了更强的推理与处理复杂指令的能力。它可接受图像和文本输入、输出文本；发布时不同功能的开放范围并不相同。',
      source: 'https://openai.com/index/gpt-4-research/',
      category: 'models',
      tier: 'major',
    },
    {
      id: 'ernie-bot',
      year: '2023',
      date: '2023-03-16',
      name: '文心一言发布',
      tag: '国产起跑',
      line: '中国大模型的春天，从一场发布会开始。',
      detail:
        '百度发布文心一言，国产大模型第一次集体亮相；随后数月，数十家厂商相继入场。',
      source: 'https://en.wikipedia.org/wiki/ERNIE_Bot',
      category: 'models',
      tier: 'minor',
    },
    {
      id: 'runway-gen2',
      year: '2023',
      date: '2023-03-20',
      name: 'Runway Gen-2',
      tag: '视频先声',
      line: '会动的画，比 Sora 早了一年。',
      detail:
        'Runway 发布 Gen-2，文本直接生成短视频，把“文生视频”从论文带进产品，宣告视频生成进入前夜。',
      source: 'https://en.wikipedia.org/wiki/Runway_(company)',
      category: 'video',
      tier: 'minor',
    },
    {
      id: 'autogpt',
      year: '2023',
      date: '2023-03-30',
      name: 'AutoGPT 爆火',
      tag: '自主狂热',
      line: '给它一个目标，它自己给自己派活。',
      detail:
        'AutoGPT 展示“自主智能体”雏形，GitHub 星标数周狂飙；也留下第一批跑偏的自动化笑话。',
      source: 'https://github.com/Significant-Gravitas/AutoGPT',
      category: 'agents',
      tier: 'minor',
    },
    {
      id: 'nvidia-1t',
      year: '2023',
      date: '2023-05-30',
      name: '英伟达市值破万亿',
      tag: '万亿市值',
      line: 'AI 越火，黄仁勋的皮衣越贵。',
      detail:
        'AI 需求推动英伟达市值突破一万亿美元，算力第一次成为全球资本的叙事主角。',
      source: 'https://en.wikipedia.org/wiki/Nvidia',
      category: 'agents',
      tier: 'minor',
    },
    {
      id: 'xai-grok-1',
      year: '2023',
      date: '2023-07-12',
      name: 'xAI 成立，Grok 登场',
      tag: '马斯克入场',
      line: '签完警告信，转头自己下场。',
      detail:
        '马斯克创立 xAI，同年 11 月发布 Grok-1 并接入 X 平台，“自带流量的模型”登场。',
      source: 'https://x.ai',
      category: 'models',
      tier: 'minor',
    },
    {
      id: 'llama-2',
      year: '2023',
      date: '2023-07-18',
      name: 'Llama 2 商用开放',
      tag: '商用开放',
      line: '基座模型，第一次白送商业使用。',
      detail:
        'Meta 发布 Llama 2 并开放商用许可，企业自建模型的大门从此打开，开源与闭源的边界开始松动。',
      source: 'https://ai.meta.com/llama/',
      category: 'open',
      tier: 'minor',
    },
    {
      id: 'dalle-3',
      year: '2023',
      date: '2023-09-20',
      name: 'DALL-E 3 进 ChatGPT',
      tag: '聊天生图',
      line: '不用学提示词，说人话就行。',
      detail:
        'DALL-E 3 内置于 ChatGPT，图像生成第一次成为对话的自然延伸。',
      source: 'https://openai.com/index/dall-e-3/',
      category: 'images',
      tier: 'minor',
    },
    {
      id: 'mistral-7b',
      year: '2023',
      date: '2023-09-27',
      name: 'Mistral 7B',
      tag: '磁力链接',
      line: '一条推文，一个 torrent，震惊业界。',
      detail:
        '法国 Mistral 以磁力链接发布 7B 开源模型，小参数打赢大参数，欧洲力量登场。',
      source: 'https://mistral.ai/news/announcing-mistral-7b',
      category: 'open',
      tier: 'minor',
    },
    {
      id: 'openai-devday',
      year: '2023',
      date: '2023-11-06',
      name: 'OpenAI 首届 DevDay',
      tag: '开发者春晚',
      line: 'GPTs、GPT-4 Turbo，还有“版权盾”。',
      detail:
        'OpenAI 首届开发者大会发布 GPT-4 Turbo 与自定义 GPTs，个人版 AI 应用生态初现雏形。',
      source: 'https://openai.com/index/openai-devday/',
      category: 'models',
      tier: 'minor',
    },
    {
      id: 'altman-saga',
      year: '2023',
      date: '2023-11-17',
      name: 'Altman 解雇风波',
      tag: '五日风波',
      line: '周五被解雇，周三回来上班。',
      detail:
        'OpenAI 董事会突然解雇 Altman，七百余名员工联名威胁集体离职，五天后戏剧性回归；治理与安全的争论延续至今。',
      source: 'https://en.wikipedia.org/wiki/November_2023_OpenAI_leadership_crisis',
      category: 'models',
      tier: 'major',
    },
    {
      id: 'gemini-1',
      year: '2023',
      date: '2023-12-06',
      name: 'Gemini 1.0',
      tag: '全家桶反击',
      line: '谷歌的正式反击，从原生多模态开始。',
      detail:
        'Google 发布 Gemini 1.0，原生多模态路线首次完整亮相，三档尺寸覆盖云端到终端。',
      source: 'https://deepmind.google/models/gemini/',
      category: 'models',
      tier: 'minor',
    },
    {
      id: 'mixtral',
      year: '2023',
      date: '2023-12-11',
      name: 'Mixtral 8x7B',
      tag: '稀疏专家',
      line: '八个专家，轮流上班。',
      detail:
        'Mistral 开源首个 MoE 稀疏专家模型，“每个 token 只激活部分参数”自此成为行业标配架构。',
      source: 'https://mistral.ai/news/mixtral-of-experts',
      category: 'open',
      tier: 'minor',
    },
    // ── 2024 ──────────────────────────────────────────────
    {
      id: 'sora',
      year: '2024',
      date: '2024-02-15',
      name: 'Sora',
      tag: '视频的新想象',
      line: '写下一段话，然后看它发生。',
      detail:
        'OpenAI 首次展示 Sora，并发布技术报告。这里记录的是研究展示节点，不代表当日已经向所有用户开放。',
      source: 'https://openai.com/index/video-generation-models-as-world-simulators/',
      category: 'video',
      tier: 'major',
    },
    {
      id: 'gemini-15',
      year: '2024',
      date: '2024-02-15',
      name: 'Gemini 1.5 Pro',
      tag: '百万上下文',
      line: '一次把整本书读完的模型来了。',
      detail:
        'Gemini 1.5 Pro 支持百万 token 上下文，长文档、长视频理解成为新战场。',
      source: 'https://deepmind.google/models/gemini/',
      category: 'models',
      tier: 'minor',
    },
    {
      id: 'claude-3',
      year: '2024',
      date: '2024-03-04',
      name: 'Claude 3',
      tag: '模型家族',
      line: '不同大小的模型，开始分工。',
      detail:
        'Anthropic 发布 Claude 3 家族：Haiku、Sonnet 和 Opus。发布当天 Sonnet 与 Opus 开放使用，Haiku 随后推出。',
      source: 'https://www.anthropic.com/news/claude-3-family',
      category: 'models',
      tier: 'major',
    },
    {
      id: 'devin',
      year: '2024',
      date: '2024-03-12',
      name: 'Devin 发布',
      tag: 'AI 工程师',
      line: '“首个 AI 软件工程师”，惊艳与质疑齐飞。',
      detail:
        'Cognition 发布 Devin，演示惊艳但随后被社区逐帧复查，成为“演示文化”讨论的标志事件。',
      source: 'https://cognition.com/blog/introducing-devin',
      category: 'agents',
      tier: 'minor',
    },
    {
      id: 'nvidia-gtc',
      year: '2024',
      date: '2024-03-18',
      name: '英伟达 GTC 与 Blackwell',
      tag: '算力军备',
      line: '“AI 界的伍德斯托克”开演。',
      detail:
        'GTC 大会发布 Blackwell 架构，算力成为明牌军备，“世界只需要三种计算机”的口号响彻会场。',
      source: 'https://www.nvidia.com/en-us/events/gtc/',
      category: 'agents',
      tier: 'minor',
    },
    {
      id: 'kimi-200w',
      year: '2024',
      date: '2024-03-18',
      name: 'Kimi 200 万字长文本',
      tag: '长文军备',
      line: '两百万字，一次读完。',
      detail:
        '月之暗面宣布 Kimi 支持 200 万字长文本输入，各家随即跟进，长上下文成为国产模型的主战场。',
      source: 'https://www.moonshot.ai',
      category: 'models',
      tier: 'minor',
    },
    {
      id: 'suno-v3',
      year: '2024',
      date: '2024-03-22',
      name: 'Suno v3',
      tag: '人人作曲',
      line: '两分钟完整歌曲，副歌都给你写好。',
      detail:
        'Suno v3 向所有用户开放，AI 音乐第一次大规模出圈，版权争议同步升温。',
      source: 'https://suno.com',
      category: 'audio',
      tier: 'minor',
    },
    {
      id: 'llama-3',
      year: '2024',
      date: '2024-04-18',
      name: 'Llama 3 开源',
      tag: '咬住闭源',
      line: '开源第一次真正咬住 GPT-4。',
      detail:
        'Meta 开源 Llama 3，七月推出 405B 版本；开源阵营首次对闭源旗舰形成实质追击。',
      source: 'https://ai.meta.com/llama/',
      category: 'open',
      tier: 'minor',
    },
    {
      id: 'gpt-4o',
      year: '2024',
      date: '2024-05-13',
      name: 'GPT-4o',
      tag: '多模态',
      line: '对话，从文字走向声音与画面。',
      detail:
        'OpenAI 发布 GPT-4o，展示了跨文本、音频与图像的实时交互方向。各项功能分阶段开放，发布演示不等于所有功能当天可用。',
      source: 'https://openai.com/index/hello-gpt-4o/',
      category: 'models',
      tier: 'major',
    },
    {
      id: 'kling',
      year: '2024',
      date: '2024-06-06',
      name: '可灵 AI 发布',
      tag: '国产黑马',
      line: '快手把“真实影像级”视频生成开给了百万人。',
      detail:
        '快手可灵开放邀测，1080p、最长两分钟的生成能力惊艳业界，一年内迭代数十次。',
      source: 'https://klingai.com',
      category: 'video',
      tier: 'minor',
    },
    {
      id: 'apple-intelligence',
      year: '2024',
      date: '2024-06-10',
      name: 'Apple Intelligence',
      tag: '苹果入场',
      line: '系统级的 AI，藏进了口袋。',
      detail:
        'WWDC 上苹果发布 Apple Intelligence，AI 首次成为十亿级设备的基础能力。',
      source: 'https://www.apple.com/apple-intelligence/',
      category: 'agents',
      tier: 'minor',
    },
    {
      id: 'claude-35',
      year: '2024',
      date: '2024-06-20',
      name: 'Claude 3.5 Sonnet 与 Artifacts',
      tag: '画布时刻',
      line: '聊天框里，第一次长出了画布。',
      detail:
        'Anthropic 发布 Claude 3.5 Sonnet，Artifacts 让对话成果直接成为可编辑的作品。',
      source: 'https://www.anthropic.com/news/claude-3-5-sonnet',
      category: 'models',
      tier: 'minor',
    },
    {
      id: 'flux',
      year: '2024',
      date: '2024-08-01',
      name: 'FLUX.1 开源',
      tag: '原班人马',
      line: 'Stable Diffusion 的缔造者们，交出了新作品。',
      detail:
        'Stable Diffusion 核心团队创立 Black Forest Labs，首发 FLUX.1 开源模型，图像生成格局再洗牌。',
      source: 'https://bfl.ai',
      category: 'images',
      tier: 'minor',
    },
    {
      id: 'notebooklm',
      year: '2024',
      date: '2024-09-11',
      name: 'NotebookLM 音频概览',
      tag: '文档播客',
      line: '两个 AI，把你的资料聊成播客。',
      detail:
        'Google NotebookLM 上线 Audio Overviews，“AI 播客”成为学习类内容的爆款形态。',
      source: 'https://blog.google/innovation-and-ai/products/notebooklm-audio-overviews/',
      category: 'audio',
      tier: 'minor',
    },
    {
      id: 'o1-preview',
      year: '2024',
      date: '2024-09-12',
      name: 'OpenAI o1',
      tag: '推理范式',
      line: '“先想一想再回答”，从此写进了提示词。',
      detail:
        'o1 系列引入思维链推理，回答前先“思考”；推理模型成为新范式，也把“等待”变成了产品的一部分。',
      source: 'https://openai.com/index/introducing-openai-o1-preview/',
      category: 'models',
      tier: 'major',
    },
    {
      id: 'qwen-25',
      year: '2024',
      date: '2024-09-19',
      name: 'Qwen2.5 开源',
      tag: '静默霸榜',
      line: '没有发布会，下载量说话。',
      detail:
        '阿里开源 Qwen2.5 系列，此后长期占据全球开源模型下载量榜首。',
      source: 'https://qwen.ai',
      category: 'open',
      tier: 'minor',
    },
    {
      id: 'ai-nobel',
      year: '2024',
      date: '2024-10-08',
      name: '诺奖之夜：连中两元',
      tag: '科学正名',
      line: '神经网络的先驱拿了物理奖，AlphaFold 拿了化学奖。',
      detail:
        'Hinton 与 Hopfield 获诺贝尔物理学奖，次日 AlphaFold 团队获化学奖；AI 的科学贡献获得最高规格背书。',
      source: 'https://www.nobelprize.org/prizes/physics/2024/summary/',
      category: 'models',
      tier: 'major',
    },
    {
      id: 'computer-use',
      year: '2024',
      date: '2024-10-22',
      name: 'Claude computer use',
      tag: '操纵电脑',
      line: '模型第一次公开演示“操作你的电脑”。',
      detail:
        'Anthropic 开放 computer use：模型可以看屏幕、点按钮、填表格，智能体的边界再次外扩。',
      source: 'https://www.anthropic.com/news/3-5-models-upgrade',
      category: 'agents',
      tier: 'minor',
    },
    {
      id: 'chatgpt-search',
      year: '2024',
      date: '2024-10-31',
      name: 'ChatGPT Search',
      tag: '搜索内战',
      line: '聊天框开始抢搜索引擎的饭碗。',
      detail:
        'ChatGPT 内置网页搜索，“问 AI 还是搜网页”的选择题第一次摆上桌面。',
      source: 'https://openai.com/index/chatgpt-search/',
      category: 'agents',
      tier: 'minor',
    },
    {
      id: 'openai-12days',
      year: '2024',
      date: '2024-12-05',
      name: 'OpenAI 12 天连更',
      tag: '十二连发',
      line: '连续十二个工作日，每天一个新东西。',
      detail:
        'OpenAI 以“12 Days of Shipmas”连续发布 o1 正式版、Canvas、Sora 正式版等，发布会通胀时代来临。',
      source: 'https://openai.com/index/12-days-of-openai/',
      category: 'models',
      tier: 'minor',
    },
    {
      id: 'sora-turbo',
      year: '2024',
      date: '2024-12-09',
      name: 'Sora Turbo',
      tag: '产品上线',
      line: '从研究展示，走向产品。',
      detail: '同年 12 月，Sora Turbo 随产品发布。首次展示与产品上线，值得分别留下一张档案卡。',
      source: 'https://openai.com/index/sora-is-here/',
      category: 'video',
      tier: 'major',
    },
    {
      id: 'deepseek-v3',
      year: '2024',
      date: '2024-12-26',
      name: 'DeepSeek-V3',
      tag: '成本震撼',
      line: '五百多万美元，训了个旗舰。',
      detail:
        'DeepSeek 发布并开源 V3，训练成本远低于同级闭源模型，为一个月后的 R1 风暴埋下伏笔。',
      source: 'https://api-docs.deepseek.com/news/news241226',
      category: 'open',
      tier: 'minor',
    },
    // ── 2025 ──────────────────────────────────────────────
    {
      id: 'deepseek-r1',
      year: '2025',
      date: '2025-01-20',
      name: 'DeepSeek-R1',
      tag: '推理的时刻',
      line: '我们开始看见，答案之前的过程。',
      detail:
        'DeepSeek 发布 R1 推理模型，并提供开放权重。一周后应用登顶美区 App Store，英伟达单日市值蒸发创纪录，被称为“DeepSeek 冲击波”。数学、代码和推理任务成为这一节点的重要关注点。',
      source: 'https://api-docs.deepseek.com/news/news250120/',
      category: 'open',
      tier: 'major',
    },
    {
      id: 'manus',
      year: '2025',
      date: '2025-03-06',
      name: 'Manus 爆火',
      tag: '邀请码时刻',
      line: '一码难求，二手平台上代抢成了生意。',
      detail:
        '国产通用 Agent 产品 Manus 引发现象级关注，“邀请码经济”成为 AI 圈新景观。',
      source: 'https://manus.im',
      category: 'agents',
      tier: 'minor',
    },
    {
      id: 'ghibli',
      year: '2025',
      date: '2025-03-25',
      name: 'GPT-4o 原生图像与吉卜力狂潮',
      tag: '全网吉卜力',
      line: 'Altman 连夜换了头像，全网都在吉卜力。',
      detail:
        'GPT-4o 原生图像生成上线，吉卜力风格二创刷屏，风格模仿与版权的争论同步爆发。',
      source: 'https://openai.com/index/introducing-4o-image-generation/',
      category: 'images',
      tier: 'major',
    },
    {
      id: 'llama-4',
      year: '2025',
      date: '2025-04-05',
      name: 'Llama 4 发布',
      tag: '期望落空',
      line: '一次没能服众的发布，和一场“开源已死”的讨论。',
      detail:
        'Llama 4 因基准争议遭遇批评，开源阵营的旗帜是否仍在 Meta 成为话题。',
      source: 'https://ai.meta.com/llama/',
      category: 'open',
      tier: 'minor',
    },
    {
      id: 'codex-cli',
      year: '2025',
      date: '2025-04-16',
      name: 'Codex CLI 与 Claude Code',
      tag: '终端里的搭档',
      line: '命令行里，住进了一位同事。',
      detail:
        'OpenAI 开源 Codex CLI，Claude Code 同期走红；编程智能体从概念变成日常工具。',
      source: 'https://github.com/openai/codex',
      category: 'agents',
      tier: 'minor',
    },
    {
      id: 'qwen-3',
      year: '2025',
      date: '2025-04-29',
      name: 'Qwen 3 开源',
      tag: '开源中坚',
      line: '悄悄更新，全球下载榜常年第一。',
      detail:
        '阿里开源 Qwen 3 系列，此后其衍生生态成为全球最活跃的开源模型家族之一。',
      source: 'https://qwen.ai',
      category: 'open',
      tier: 'minor',
    },
    {
      id: 'veo-3',
      year: '2025',
      date: '2025-05-21',
      name: 'Veo 3',
      tag: '有声视频',
      line: 'AI 视频，第一次自带声音。',
      detail:
        'Google I/O 发布 Veo 3，对白、音效与画面同步生成，AI 视频的“无声默片时代”结束。',
      source: 'https://finance.sina.com.cn/stock/usstock/c/2025-05-21/doc-inexhfyr3220941.shtml',
      category: 'video',
      tier: 'major',
    },
    {
      id: 'claude-4',
      year: '2025',
      date: '2025-05-22',
      name: 'Claude 4（Opus 4）',
      tag: '长跑选手',
      line: '模型开始学会连续干几个小时的活。',
      detail:
        'Anthropic 发布 Claude 4 系列，长时间自主任务能力成为主打卖点。',
      source: 'https://www.anthropic.com/news/claude-4',
      category: 'models',
      tier: 'minor',
    },
    {
      id: 'grok-4',
      year: '2025',
      date: '2025-07-09',
      name: 'Grok 4',
      tag: '火力全开',
      line: 'Heavy 版两个模型对答，榜单一路狂飙。',
      detail:
        'xAI 发布 Grok 4，宣称多项基准登顶；发布会的攻击性风格同样成为话题。',
      source: 'https://x.ai/news/grok-4',
      category: 'models',
      tier: 'minor',
    },
    {
      id: 'kimi-k2',
      year: '2025',
      date: '2025-07-11',
      name: 'Kimi K2 开源',
      tag: '万亿开源',
      line: '一万亿参数，直接开源。',
      detail:
        '月之暗面开源 1T 参数 MoE 基础模型 Kimi K2，agentic 能力开箱可用，日调用量迅速破百亿 token。',
      source: 'https://finance.sina.com.cn/roll/2025-07-13/doc-inffikpm7017615.shtml',
      category: 'open',
      tier: 'minor',
    },
    {
      id: 'chatgpt-agent',
      year: '2025',
      date: '2025-07-17',
      name: 'ChatGPT Agent',
      tag: '自己动手',
      line: '从“告诉你怎么做”，到“我帮你做了”。',
      detail:
        'OpenAI 推出 ChatGPT Agent，在虚拟机里浏览、填表、订票一站完成。',
      source: 'https://openai.com/index/introducing-chatgpt-agent/',
      category: 'agents',
      tier: 'minor',
    },
    {
      id: 'gpt-5',
      year: '2025',
      date: '2025-08-07',
      name: 'GPT-5',
      tag: '两年之约',
      line: '传闻了两年，它终于来了。',
      detail:
        'GPT-5 正式发布，统一对话与推理体验，“模型路由”成为新架构叙事。',
      source: 'https://openai.com/index/introducing-gpt-5/',
      category: 'models',
      tier: 'major',
    },
    {
      id: 'nano-banana',
      year: '2025',
      date: '2025-08-26',
      name: 'Nano Banana 出圈',
      tag: '一根香蕉',
      line: '匿名竞技场里，一根香蕉统治了图表。',
      detail:
        '谷歌 Gemini 2.5 Flash Image 以“纳米香蕉”代号在匿名评测中登顶，角色一致性与编辑能力出圈。',
      source: 'https://www.cls.cn/detail/2131738',
      category: 'images',
      tier: 'minor',
    },
    {
      id: 'sora-2',
      year: '2025',
      date: '2025-09-30',
      name: 'Sora 2 与独立 App',
      tag: '视频大众化',
      line: '物理靠谱了，还自带音效。',
      detail:
        'OpenAI 发布 Sora 2 与独立应用，“社交视频生成”的形态第一次完整落地。',
      source: 'https://openai.com/index/sora-2/',
      category: 'video',
      tier: 'major',
    },
    {
      id: 'gpt-51',
      year: '2025',
      date: '2025-11-12',
      name: 'GPT-5.1',
      tag: '说人话',
      line: '不跑分、不刷榜，主打说人话。',
      detail:
        'OpenAI 发布 GPT-5.1，宣称回归对话质感而非榜单数字，一周内面向所有用户免费开放。',
      source: 'https://openai.com/zh-Hans-CN/index/gpt-5-1/',
      category: 'models',
      tier: 'minor',
    },
    {
      id: 'gemini-3',
      year: '2025',
      date: '2025-11-18',
      name: 'Gemini 3 Pro',
      tag: '谷歌逆袭',
      line: '发布会之后，Gemini 站上了应用商店榜首。',
      detail:
        'Google 发布 Gemini 3，原生多模态与深度思考能力全面对标，移动端声量反超。',
      source: 'http://www.news.cn/tech/20251120/fe871e40a8ae4865b25ed101802d0071/c.html',
      category: 'models',
      tier: 'major',
    },
    {
      id: 'opus-45',
      year: '2025',
      date: '2025-11-24',
      name: 'Claude Opus 4.5',
      tag: '王座易主',
      line: '编码王座，开始以“周”为单位换人坐。',
      detail:
        'Anthropic 发布 Opus 4.5，SWE 类基准反超 Gemini 3 与 GPT-5.1，成为全线产品默认模型。',
      source: 'https://www.anthropic.com/news/claude-opus-4-5',
      category: 'models',
      tier: 'minor',
    },
    // ── 2026 ──────────────────────────────────────────────
    {
      id: 'deepseek-v4-open',
      year: '2026',
      date: '2026-04-24',
      name: 'DeepSeek-V4 开源',
      tag: '再次比肩',
      line: '价格只有 GPT-5.5 的三十分之一。',
      detail:
        'DeepSeek 发布并开源 V4 预览版：1.6 万亿参数、百万 token 上下文，SWE-bench 80.6%，开源再次追平闭源旗舰。',
      source: 'https://www.guancha.cn/economy/2026_04_24_814797.shtml',
      category: 'open',
      tier: 'major',
    },
    {
      id: 'agent-harness',
      year: '2026',
      date: '2026-04-30',
      name: 'Agent = Model + Harness',
      tag: '框架主角',
      line: '大家发现：模型之外，框架才是落地的另一半。',
      detail:
        'Cursor 发文阐述持续改进智能体框架的方法论，“Agent = Model + Harness”成为行业共识，竞争从模型层蔓延到基础设施。',
      source: 'https://cursor.com/cn/blog/continually-improving-agent-harness',
      category: 'agents',
      tier: 'major',
    },
    {
      id: 'glm-52',
      year: '2026',
      date: '2026-06-17',
      name: 'GLM-5.2 开源',
      tag: '开源平替',
      line: '“Claude 级编程能力的开源平替”。',
      detail:
        '智谱开源 GLM-5.2，7400 亿参数主打编程与智能体，海外社区反响热烈。',
      source: 'https://zhuanlan.zhihu.com/p/2050733508507833888',
      category: 'open',
      tier: 'minor',
    },
    {
      id: 'kimi-k3',
      year: '2026',
      date: '2026-07-16',
      name: 'Kimi K3 发布',
      tag: '全球股灾',
      line: '2.8 万亿参数开源，全球科技股三天蒸发约四千七百亿美元。',
      detail:
        '月之暗面发布 K3 并于十日后开源完整权重，成为当时全球最大的开源模型；资本市场以连续暴跌回应，被称为 2026 年的“DeepSeek 时刻”。',
      source: 'https://www.tmtpost.com/8074132.html',
      category: 'open',
      tier: 'major',
    },
    {
      id: 'opus-5',
      year: '2026',
      date: '2026-07-24',
      name: 'Claude Opus 5',
      tag: '半价旗舰',
      line: '旗舰智能，半价出售。',
      detail:
        'Anthropic 发布 Opus 5，智能对标自家旗舰而价格减半，“前沿平民化”成为主题。',
      source: 'https://www.anthropic.com/news/claude-opus-5',
      category: 'models',
      tier: 'minor',
    },
    {
      id: 'deepseek-v4-pro',
      year: '2026',
      date: '2026-08-13',
      name: 'DeepSeek V4 Pro 正式版',
      tag: '正式交卷',
      line: '预览版的答卷，正式交卷。',
      detail:
        'V4 Pro 正式版在 App、网页与 API 同步上线，“专家模式”成为默认选项。',
      source: 'https://api-docs.deepseek.com/zh-cn/news/news260813/',
      category: 'models',
      tier: 'minor',
    },
    {
      id: 'gemini-38',
      year: '2026',
      date: '2026-09-02',
      name: 'Gemini 3.8 Flash',
      tag: '白菜上下文',
      line: '百万 token 上下文，卖出了白菜价。',
      detail:
        'Google 发布 Gemini 3.8 Flash，百万上下文与低价组合，主打“干活模型”。',
      source: 'https://blog.google/innovation-and-ai/models-and-research/gemini-models/3-8-flash-and-3-8-flash-cyber/',
      category: 'models',
      tier: 'minor',
    },
    {
      id: 'gpt-6-astra',
      year: '2026',
      date: '2026-09-03',
      name: 'GPT-6 Astra',
      tag: 'Critical 时刻',
      line: '第一个被称作“Critical”的模型，晚到了四周。',
      detail:
        'OpenAI 发布 GPT-6 Astra，称能力触及关键阈值，因网络安全评估推迟四周上线；API、Azure 与 Bedrock 同步开放。',
      source: 'https://openai.com/index/gpt-6-astra/',
      category: 'models',
      tier: 'major',
    },
    {
      id: 'ai-outage',
      year: '2026',
      date: '2026-09-03',
      name: '黑色星期四大宕机',
      tag: '基建现形',
      line: 'ChatGPT、Claude、Grok，同一个下午一起挂了。',
      detail:
        '北美时间周四下午，三家头部 AI 服务同时中断约三小时四十分钟，约 3.7 万份故障报告，Cursor 等下游产品连带受累；AI 基础设施的脆弱性第一次大规模现形。',
      source: 'https://m.21jingji.com/article/20260904/herald/4b1de4e859674d1b41efdd1ccbbe4c00_zaker.html',
      category: 'agents',
      tier: 'major',
    },
  ] satisfies TimelineEvent[]
).sort((a, b) => a.date.localeCompare(b.date));

// 每个年份的主展品 id：该年在时间线上置顶打头。
const eraAnchors = ['chatgpt', 'gpt-4', 'sora', 'deepseek-r1', 'gpt-6-astra'] as const;

export const eras = [
  {
    year: '2022',
    title: '一切，从一句你好开始。',
    subtitle: '我们第一次发现，和电脑聊天，可以不只是聊天。',
    note: '当时觉得：能写出一整段像样的话，就已经很厉害了。',
  },
  {
    year: '2023',
    title: '从能聊天，到能帮忙。',
    subtitle: '问题变长了，期待也变高了。我们开始把工作交给它。',
    note: '回头看，最先改变的可能不是工作，而是我们提问题的方式。',
  },
  {
    year: '2024',
    title: '想象，开始动起来。',
    subtitle: '文字之外，我们开始期待会动的世界。',
    note: '以前问“这张图是真的吗”，后来还得再问一句“这段视频呢”。',
  },
  {
    year: '2025',
    title: '答案之前，多了一段思考。',
    subtitle: '推理模型走进更多人的日常，等待也有了新的意义。',
    note: '“稍等，我想一想。”这句话，电脑也开始说了。',
  },
  {
    year: '2026',
    title: '快，追不上标题了。',
    subtitle: '发布节奏快过新闻周期，“最强”的保质期开始按天计算。',
    note: '有统计称年初四十七天里发生三十多次模型更新；然后“黑色星期四”提醒所有人：跑得再快，地基也会塌。',
  },
].map((era, i) => ({
  ...era,
  tag: events.find((e) => e.id === eraAnchors[i])?.tag ?? '',
}));

// 时间线按年份取展品：该年的主展品置顶（叙事打头），其余按日期排序。
export function eventsInYear(year: string): TimelineEvent[] {
  const anchorIndex = eras.findIndex((era) => era.year === year);
  const anchorId = anchorIndex >= 0 ? eraAnchors[anchorIndex] : undefined;
  const list = events.filter((e) => e.year === year);
  const anchor = anchorId ? list.find((e) => e.id === anchorId) : undefined;
  return anchor ? [anchor, ...list.filter((e) => e.id !== anchorId)] : list;
}

export const categories: { id: CategoryId; name: string; description: string }[] = [
  { id: 'models', name: '对话与推理', description: '从第一句你好，到更复杂的问题。' },
  { id: 'images', name: '图像生成', description: '把一句话变成图像，保存最初的想象。' },
  { id: 'video', name: '视频生成', description: '当静止的画面开始拥有时间。' },
  { id: 'audio', name: '声音与音乐', description: '从听懂人话，到开口唱歌。' },
  { id: 'agents', name: '智能体与工具', description: '从回答问题，到替你动手。' },
  { id: 'open', name: '开源时刻', description: '把探索的机会，交给更多人。' },
];

export function dateLabel(date: string) {
  const [y, m, d] = date.split('-');
  return y + ' 年 ' + Number(m) + ' 月 ' + Number(d) + ' 日';
}
